### ISSUE TITLE
`null` handling throws an error

### ISSUE THREAD

**Issue by Turbo87** [ozkxr/match-json#17] opened 2021-09-21 09:24 UTC
If a value is `null`, which has `typeof null === "object"` it leads to:
https://github.com/ozkxr/match-json/blob/49fea96299195fb1d514697053a9de48db8b23d9/lib/match.js#L28-L29 
which leads to:
https://github.com/ozkxr/match-json/blob/49fea96299195fb1d514697053a9de48db8b23d9/lib/match.js#L65-L68
and that breaks because `Object.keys(null)` throws:

> TypeError: Cannot convert undefined or null to object

**Comment by ozkxr** [comment] 2021-11-21 18:29
First, I'm really sorry for addressing this until now. I had not noticed there was an open issue.
All my apologies, I got no excuse.

I tried to reproduce this bug this way:
```
var abc = null;
match(abc, null) //=> true
```

And it works for me. Maybe I'm not reproducing it the right way.

Can you provide me some code so I can reproduce the bug?

Also, it would be helpful to know which version of the lib you are using.

Thanks for opening this issue and, again, my apologies for the late, late reply.

**Comment by ozkxr** [comment] 2022-01-26 15:48
I'm closing this but if your problem persist, please get in touch, re-open this issue or file another. Again, sorry for the late response.

**Closed as completed by ozkxr** 2022-01-26 15:48 UTC
